export const PROTOCOL_BET_ABI = [
  // ── READ ──
  {
    name: 'counter',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'getDuel',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{
      name: '',
      type: 'tuple',
      components: [
        { name: 'red', type: 'address' },
        { name: 'blue', type: 'address' },
        { name: 'token', type: 'address' },
        { name: 'wager', type: 'uint256' },
        { name: 'audioBps', type: 'uint256' },
        { name: 'deadline', type: 'uint256' },
        { name: 'claimHash', type: 'bytes32' },
        { name: 'ruleHash', type: 'bytes32' },
        { name: 'vis', type: 'uint8' },
        { name: 'status', type: 'uint8' },
        { name: 'winner', type: 'uint8' },
        { name: 'settledAt', type: 'uint256' },
      ],
    }],
  },
  {
    name: 'poolRed',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'poolBlue',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'betRed',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }, { name: 'addr', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'betBlue',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }, { name: 'addr', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'claimed',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }, { name: 'addr', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  // ── WRITE ──
  {
    name: 'create',
    type: 'function',
    stateMutability: 'payable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'wager', type: 'uint256' },
      { name: 'audioBps', type: 'uint256' },
      { name: 'duration', type: 'uint256' },
      { name: 'claimHash', type: 'bytes32' },
      { name: 'ruleHash', type: 'bytes32' },
      { name: 'vis', type: 'uint8' },
    ],
    outputs: [{ name: 'id', type: 'uint256' }],
  },
  {
    name: 'accept',
    type: 'function',
    stateMutability: 'payable',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'bet',
    type: 'function',
    stateMutability: 'payable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'side', type: 'uint8' },
      { name: 'amt', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'claim',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'cancel',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'dispute',
    type: 'function',
    stateMutability: 'payable',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'settle',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'winner', type: 'uint8' },
    ],
    outputs: [],
  },
  // ── EVENTS ──
  {
    name: 'Created',
    type: 'event',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'red', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'wager', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'Accepted',
    type: 'event',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'blue', type: 'address', indexed: true },
    ],
  },
  {
    name: 'Settled',
    type: 'event',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'winner', type: 'uint8', indexed: false },
    ],
  },
  {
    name: 'Claimed',
    type: 'event',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'amt', type: 'uint256', indexed: false },
    ],
  },
] as const;
